[package]
name = "metriken"
version = "0.1.0"
edition = "2021"
authors = [
	"Brian Martin <brayniac@gmail.com>",
	"Sean Lynch <seanl@twitter.com>",
]
license = "Apache-2.0"
description = "A fast and lightweight metrics library"
homepage = "https://github.com/pelikan-io/rustcommon"
repository = "https://github.com/pelikan-io/rustcommon"

[dependencies]
clocksource = "0.6.0"
heatmap = "0.7.0"
linkme = "0.3.3"
once_cell = "1.14.0"
parking_lot = "0.12.1"
metriken-derive = "0.1.0"
