[package]
name = "rustcommon-logger"
version = "0.1.1"
edition = "2018"
homepage = "https://github.com/pelikan-io/rustcommon/logger"
repository = "https://github.com/pelikan-io/rustcommon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.0"
clocksource = { path = "../clocksource" }
metriken = { path = "../metriken" }
log = { version = "0.4.17", features = ["std"] }
mpmc = "0.1.6"
